import { Conversation } from '../models/Conversation.js';
import { Message } from '../models/Message.js';
import { Product } from '../models/Product.js';
import { persistUpload } from '../middlewares/upload.js';
import { ApiError } from '../utils/ApiError.js';
import { asyncHandler } from '../utils/asyncHandler.js';

const idValue = (value) => value?._id?.toString() || value?.toString();
const participant = (conversation, userId) => idValue(conversation.buyer) === userId.toString() || idValue(conversation.seller) === userId.toString();
const getConversation = async (id) => Conversation.findById(id).populate('buyer seller', 'name avatar role').populate('product', 'name company images');
const listConversations = asyncHandler(async (request, response) => response.json({ ok: true, data: await Conversation.find({ $or: [{ buyer: request.user._id }, { seller: request.user._id }] }).populate('buyer seller', 'name avatar role').populate('product', 'name company images').sort({ updatedAt: -1 }) }));
const startConversation = asyncHandler(async (request, response) => { const product = await Product.findById(request.body.productId); if (!product) throw new ApiError(404, 'Producto no encontrado'); if (product.owner.toString() === request.user._id.toString()) throw new ApiError(403, 'No puedes chatear contigo mismo'); const conversation = await Conversation.findOneAndUpdate({ product: product._id, buyer: request.user._id, seller: product.owner }, { $setOnInsert: { product: product._id, buyer: request.user._id, seller: product.owner } }, { upsert: true, new: true, setDefaultsOnInsert: true }); response.status(201).json({ ok: true, data: await getConversation(conversation._id) }); });
const messages = asyncHandler(async (request, response) => { const conversation = await getConversation(request.params.id); if (!conversation) throw new ApiError(404, 'Conversación no encontrada'); if (request.user.role !== 'admin' && !participant(conversation, request.user._id)) throw new ApiError(403, 'Esta conversación no pertenece a tu cuenta'); response.json({ ok: true, data: { conversation, messages: await Message.find({ conversation: conversation._id }).populate('sender', 'name avatar').sort({ createdAt: 1 }) } }); });
const sendMessage = asyncHandler(async (request, response) => { const conversation = await Conversation.findById(request.params.id); if (!conversation || !participant(conversation, request.user._id)) throw new ApiError(403, 'No tienes acceso'); if (!request.body.text?.trim() && !request.file) throw new ApiError(422, 'Escribe un mensaje o adjunta una imagen'); const imageUrl = request.file ? await persistUpload(request.file) : undefined; const message = await Message.create({ conversation: conversation._id, sender: request.user._id, text: request.body.text?.trim() || '', image: imageUrl || undefined }); const recipient = conversation.buyer.toString() === request.user._id.toString() ? 'seller' : 'buyer'; conversation.lastMessage = { text: message.text || 'Imagen', senderId: request.user._id, createdAt: message.createdAt }; conversation[`unread${recipient[0].toUpperCase()}${recipient.slice(1)}`] += 1; await conversation.save(); const populated = await message.populate('sender', 'name avatar'); request.app.get('io')?.to(`conversation:${conversation._id}`).emit('message:new', populated); response.status(201).json({ ok: true, data: populated }); });
const deleteMessage = asyncHandler(async (request, response) => { const message = await Message.findById(request.params.messageId); if (!message) throw new ApiError(404, 'Mensaje no encontrado'); const conversation = await Conversation.findById(message.conversation); if (!conversation || (request.user.role !== 'admin' && !participant(conversation, request.user._id))) throw new ApiError(403, 'No tienes acceso'); if (message.sender.toString() !== request.user._id.toString() && request.user.role !== 'admin') throw new ApiError(403, 'Solo puedes eliminar tus mensajes'); await message.deleteOne(); request.app.get('io')?.to(`conversation:${conversation._id}`).emit('message:deleted', { conversationId: conversation._id, messageId: message._id }); response.json({ ok: true, message: 'Mensaje eliminado' }); });
const deleteConversation = asyncHandler(async (request, response) => { const conversation = await Conversation.findById(request.params.id); if (!conversation || (request.user.role !== 'admin' && !participant(conversation, request.user._id))) throw new ApiError(403, 'No tienes acceso'); await Message.deleteMany({ conversation: conversation._id }); await conversation.deleteOne(); response.json({ ok: true, message: 'Conversación eliminada' }); });
export { listConversations, startConversation, messages, sendMessage, deleteConversation, deleteMessage, participant };
