import { Review } from '../models/Review.js';
import { Product } from '../models/Product.js';
import { ApiError } from '../utils/ApiError.js';
import { asyncHandler } from '../utils/asyncHandler.js';

const refreshRating = async (productId) => { const result = await Review.aggregate([{ $match: { product: productId } }, { $group: { _id: null, average: { $avg: '$stars' }, count: { $sum: 1 } } }]); await Product.findByIdAndUpdate(productId, { rating: result[0] ? { average: Number(result[0].average.toFixed(1)), count: result[0].count } : { average: 0, count: 0 } }); };
const listReviews = asyncHandler(async (request, response) => { const productId = request.params.productId; const reviews = await Review.find({ product: productId }).populate('author', 'name avatar').sort({ createdAt: -1 }); const summary = reviews.reduce((result, review) => { result.count += 1; result.average += review.stars; result.distribution[review.stars] += 1; return result; }, { count: 0, average: 0, distribution: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 } }); if (summary.count) summary.average = Number((summary.average / summary.count).toFixed(1)); response.json({ ok: true, data: { reviews, summary } }); });
const createReview = asyncHandler(async (request, response) => { const product = await Product.findById(request.params.productId); if (!product) throw new ApiError(404, 'Producto no encontrado'); if (product.owner.toString() === request.user._id.toString()) throw new ApiError(403, 'No puedes reseñar tu propio producto'); try { const review = await Review.create({ product: product._id, author: request.user._id, stars: request.body.stars, text: request.body.text }); await refreshRating(product._id); response.status(201).json({ ok: true, data: await review.populate('author', 'name avatar'), message: 'Reseña publicada' }); } catch (error) { if (error.code === 11000) throw new ApiError(409, 'Ya reseñaste este producto'); throw error; } });
const deleteReview = asyncHandler(async (request, response) => { const review = await Review.findById(request.params.id); if (!review) throw new ApiError(404, 'Reseña no encontrada'); if (request.user.role !== 'admin' && review.author.toString() !== request.user._id.toString()) throw new ApiError(403, 'No tienes permisos'); await review.deleteOne(); await refreshRating(review.product); response.json({ ok: true, message: 'Reseña eliminada' }); });
export { listReviews, createReview, deleteReview };
