import { checkSession, login, logout, register } from './auth.js';
import { api } from './api.js';
import { getState } from './store.js';
import { icon, setLoading, showToast } from './ui.js';
import { loadCategories, loadProducts, productState, renderProducts, toggleFavorite } from './products.js';
import { bindReviews, loadReviews, reviewsSection } from './reviews.js';
import { bindChat, initChat, openChat, renderChat } from './chat.js';
import { bindDashboard, renderDashboard } from './dashboard.js';
import { API_ORIGIN } from './config.js';
import { bindSettings } from './settings.js';

const app = document.querySelector('#app');
let authMode = 'login';
const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
const mediaUrl = (value) => value?.startsWith('http') ? value : `${API_ORIGIN}${value || ''}`;
const field = (id, label, type = 'text', autocomplete = '') => `<div class="form-field"><label for="${id}">${label}</label><div class="${type === 'password' ? 'password-wrap' : ''}"><input class="input" id="${id}" name="${id}" type="${type}" ${autocomplete ? `autocomplete="${autocomplete}"` : ''} required></div><span class="field-error" data-error-for="${id}" aria-live="polite"></span></div>`;
const passwordField = (id, label, autocomplete) => `<div class="form-field"><label for="${id}">${label}</label><div class="password-wrap"><input class="input" id="${id}" name="${id}" type="password" autocomplete="${autocomplete}" required><button class="password-toggle" type="button" data-password="${id}" aria-label="Mostrar contraseña">${icon('eye')}</button></div><span class="field-error" data-error-for="${id}" aria-live="polite"></span></div>`;
const validateField = (input, form) => { let message = ''; if (input.id === 'name' && !/^[\p{L} ]{2,80}$/u.test(input.value.trim())) message = 'Escribe un nombre válido.'; if (input.id === 'email' && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.value.trim())) message = 'Introduce un correo válido.'; if (input.id === 'password' && !/(?=.*[A-Za-z])(?=.*\d).{6,}/.test(input.value)) message = 'Usa 6 caracteres, una letra y un número.'; if (input.id === 'passwordConfirmation' && input.value !== form.password.value) message = 'Las contraseñas no coinciden.'; if (input.name === 'terms' && !input.checked) message = 'Debes aceptar los términos.'; const error = document.querySelector(`[data-error-for="${input.id}"]`); input.classList.toggle('input-error', Boolean(message)); input.classList.toggle('input-success', !message && input.value.length > 0); if (error) error.textContent = message; return !message; };
const renderAuth = () => { const isLogin = authMode === 'login'; app.className = 'auth-shell'; app.innerHTML = `<section class="auth-layout"><div class="auth-panel"><a class="brand" href="#/login"><span class="brand-mark">K</span>Konekta</a><div class="auth-heading"><h1>${isLogin ? 'Inicia sesión' : 'Crea tu cuenta'}</h1><p>${isLogin ? 'Entra para continuar donde lo dejaste.' : 'Conecta con oportunidades cerca de ti.'}</p></div><form class="auth-form" id="auth-form" novalidate>${isLogin ? `${field('email', 'Correo electrónico', 'email', 'email')}${passwordField('password', 'Contraseña', 'current-password')}<button class="btn btn-ghost" type="button" data-switch="register">¿No tienes cuenta? Regístrate</button>` : `${field('name', 'Nombre completo', 'text', 'name')}${field('email', 'Correo electrónico', 'email', 'email')}${passwordField('password', 'Contraseña', 'new-password')}${passwordField('passwordConfirmation', 'Confirmar contraseña', 'new-password')}<fieldset class="role-fieldset"><legend>Quiero</legend><div class="role-options"><label class="role-choice"><input type="radio" name="role" value="consumidor" checked> Comprar</label><label class="role-choice"><input type="radio" name="role" value="vendedor"> Vender</label></div></fieldset><label class="check-label"><input type="checkbox" name="terms" required> Acepto los términos</label><button class="btn btn-ghost" type="button" data-switch="login">¿Ya tienes cuenta? Inicia sesión</button>`}<button class="btn btn-primary" id="submit-button" type="submit">${isLogin ? 'Ingresar' : 'Crear cuenta'}</button></form><div class="form-footer">Konekta <span aria-hidden="true">·</span> Acceso seguro</div></div><aside class="auth-aside"><span class="auth-aside-mark">K</span><h2>Conecta mejor.</h2><p>Productos, servicios y personas en un solo lugar.</p></aside></section>`; bindAuth(isLogin); };
const bindAuth = (isLogin) => { const form = document.querySelector('#auth-form'); form.querySelectorAll('[data-switch]').forEach((button) => button.addEventListener('click', () => { authMode = button.dataset.switch; renderAuth(); })); form.querySelectorAll('[data-password]').forEach((button) => button.addEventListener('click', () => { const input = document.querySelector(`#${button.dataset.password}`); input.type = input.type === 'password' ? 'text' : 'password'; })); form.querySelectorAll('input').forEach((input) => input.addEventListener(input.type === 'checkbox' ? 'change' : 'input', () => validateField(input, form))); form.addEventListener('submit', async (event) => { event.preventDefault(); const valid = [...form.querySelectorAll('input[required]')].filter((input) => input.type !== 'radio').every((input) => validateField(input, form)); if (!valid) return; const button = form.querySelector('#submit-button'); setLoading(button, true, isLogin ? 'Ingresando...' : 'Creando...'); try { const data = new FormData(form); if (isLogin) await login(data.get('email').trim(), data.get('password')); else await register({ name: data.get('name').trim(), email: data.get('email').trim(), password: data.get('password'), passwordConfirmation: data.get('passwordConfirmation'), role: data.get('role') }); location.hash = '#/home'; showToast('Sesión iniciada', 'success'); } catch (error) { setLoading(button, false, isLogin ? 'Ingresar' : 'Crear cuenta'); showToast(error.message); } }); };
const header = () => { const user = getState().user; const avatar = user.avatar ? `<img src="${escapeHtml(mediaUrl(user.avatar))}" alt="${escapeHtml(user.name)}">` : escapeHtml(user.name[0]); return `<header class="site-header"><a class="brand" href="#/home"><span class="brand-mark">K</span>Konekta</a><div class="header-search"><input class="input" id="search-input" placeholder="Buscar productos o servicios" aria-label="Buscar"></div><nav class="header-nav"><a href="#/home">Explorar</a>${user.role === 'vendedor' || user.role === 'admin' ? `<a href="#/dashboard">Panel</a>` : ''}${user.role === 'admin' ? `<a href="#/admin">Admin</a>` : ''}<button class="avatar" id="avatar-menu" aria-label="Cuenta">${avatar}</button><button class="btn btn-ghost" id="logout-button">Salir</button></nav></header>`; };
const renderHome = async () => { app.className = 'app-shell'; app.innerHTML = `${header()}<main class="main-content"><section class="hero-strip"><div><p class="eyebrow">Konekta para lo que necesitas</p><h1>Encuentra lo que necesitas.</h1><p>Compra productos o contrata servicios de personas confiables.</p></div></section><div class="type-row" id="type-row"><button class="category-pill is-active" data-listing-type="">Todo</button><button class="category-pill" data-listing-type="product">Productos</button><button class="category-pill" data-listing-type="service">Servicios</button></div><div class="category-row" id="category-row"><button class="category-pill is-active" data-category="">Todas las categorías</button></div><section class="filter-bar"><button class="btn btn-secondary" id="filter-toggle">Filtros</button><select class="input compact-select" id="sort-select"><option value="recent">Más recientes</option><option value="price_asc">Precio menor</option><option value="price_desc">Precio mayor</option><option value="name">Nombre A-Z</option></select></section><section class="products-grid" id="products-grid"><div class="skeleton-card"></div><div class="skeleton-card"></div><div class="skeleton-card"></div><div class="skeleton-card"></div></section></main>${renderChat()}`; await loadCategories(); document.querySelector('#category-row').insertAdjacentHTML('beforeend', productState.categories.map((category) => `<button class="category-pill" data-category="${escapeHtml(category.name)}" data-category-type="${category.listingType}">${escapeHtml(category.name)} <small>${category.productCount}</small></button>`).join('')); await refreshProducts(); bindHome(); bindSettings(); initChat(); await bindChat(); };
const refreshProducts = async () => { try { await loadProducts(); renderProducts(document.querySelector('#products-grid')); bindProductActions(); } catch (error) { showToast(error.message); } };
const bindProductActions = () => { document.querySelectorAll('[data-favorite]').forEach((button) => button.addEventListener('click', async () => { try { await toggleFavorite(button.dataset.favorite); await refreshProducts(); } catch (error) { showToast(error.message); } })); document.querySelectorAll('[data-chat-product]').forEach((button) => button.addEventListener('click', () => openChat(button.dataset.chatProduct))); document.querySelector('[data-clear-filters]')?.addEventListener('click', () => { productState.filters = { ...productState.filters, search: '', category: '', page: 1 }; refreshProducts(); }); };
const locationLink = (location) => { if (!location?.address && !location?.lat) return ''; const target = location.lat && location.lng ? `${location.lat},${location.lng}` : location.address; return `<div class="product-location"><span>${escapeHtml(location.address || 'Ubicación disponible')}</span><a class="btn btn-secondary" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(target)}" target="_blank" rel="noreferrer">Ver mapa</a></div>`; };
const scheduleBlock = (schedule) => { const days = [['monday','Lunes'],['tuesday','Martes'],['wednesday','Miércoles'],['thursday','Jueves'],['friday','Viernes'],['saturday','Sábado'],['sunday','Domingo']].filter(([key]) => schedule?.[key]); return days.length ? `<div class="product-schedule"><strong>Horario de atención</strong>${days.map(([key, label]) => `<span><b>${label}</b>${escapeHtml(schedule[key])}</span>`).join('')}</div>` : ''; };
const bindHome = () => { let timer; document.querySelector('#search-input').addEventListener('input', (event) => { clearTimeout(timer); timer = setTimeout(() => { productState.filters.search = event.target.value; productState.filters.page = 1; refreshProducts(); }, 400); }); document.querySelector('#sort-select').addEventListener('change', (event) => { productState.filters.sort = event.target.value; refreshProducts(); }); document.querySelectorAll('[data-listing-type]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-listing-type]').forEach((item) => item.classList.remove('is-active')); button.classList.add('is-active'); productState.filters.listingType = button.dataset.listingType; productState.filters.category = ''; document.querySelectorAll('[data-category]').forEach((item) => item.classList.toggle('is-hidden', item.dataset.category && item.dataset.categoryType !== button.dataset.listingType)); document.querySelectorAll('[data-category]').forEach((item) => item.classList.remove('is-active')); document.querySelector('[data-category=""]').classList.add('is-active'); productState.filters.page = 1; refreshProducts(); })); document.querySelectorAll('[data-category]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-category]').forEach((item) => item.classList.remove('is-active')); button.classList.add('is-active'); productState.filters.category = button.dataset.category; productState.filters.page = 1; refreshProducts(); })); document.querySelector('#logout-button').addEventListener('click', async () => { await logout(); location.hash = '#/login'; }); };
const renderProduct = async (id) => { const product = (await api.get(`/products/${id}`)).data; const reviews = await loadReviews(id); app.className = 'app-shell'; app.innerHTML = `${header()}<main class="main-content product-page"><a class="back-link" href="#/home">← Volver</a><section class="product-detail"><div class="detail-gallery"><img src="${product.images?.[0] ? escapeHtml(mediaUrl(product.images[0])) : './assets/placeholder.svg'}" onerror="this.onerror=null;this.src='./assets/placeholder.svg'" alt="${escapeHtml(product.name)}"></div><div class="detail-info"><p class="eyebrow">${escapeHtml(product.listingType === 'service' ? 'Servicio' : 'Producto')} · ${escapeHtml(product.category)}</p><h1>${escapeHtml(product.name)}</h1><p class="product-company">${escapeHtml(product.company)}</p><p class="detail-description">${escapeHtml(product.desc)}</p><div class="detail-price">$${Number(product.price).toLocaleString('es-MX')}</div><span class="stock-badge">${product.stock > 0 ? `${product.stock} disponibles` : 'Agotado'}</span>${locationLink(product.location)}${scheduleBlock(product.schedule)}${product.contactPhone ? `<a class="contact-phone" href="tel:${escapeHtml(product.contactPhone)}">Llamar: ${escapeHtml(product.contactPhone)}</a>` : ''}<div class="detail-actions"><button class="btn btn-primary" data-detail-chat="${product._id}">Chatear con vendedor</button><button class="btn btn-secondary">Agregar al carrito</button></div></div></section>${reviewsSection(id, reviews)}</main>${renderChat()}`; bindSettings(); document.querySelector('[data-detail-chat]').addEventListener('click', () => openChat(id).catch((error) => showToast(error.message))); const refreshReviews = async () => { const updated = await loadReviews(id); document.querySelector('#reviews').outerHTML = reviewsSection(id, updated); bindReviews(id, refreshReviews); }; bindReviews(id, refreshReviews); initChat(); await bindChat(); };
const renderDashboardView = async (admin) => { app.className = 'app-shell'; app.innerHTML = `${header()}<main class="main-content">${await renderDashboard(admin)}</main>`; bindSettings(); bindDashboard(() => renderDashboardView(admin)); };
const renderRoute = async () => { const route = location.hash.replace(/^#\/?/, '') || (getState().user ? 'home' : 'login'); if (!getState().user && !['login', 'register'].includes(route)) { location.hash = '#/login'; return; } if (['login', 'register'].includes(route)) { authMode = route; renderAuth(); return; } try { if (route === 'home') await renderHome(); else if (route.startsWith('product/')) await renderProduct(route.split('/')[1]); else if (route === 'dashboard') { if (!['vendedor', 'admin'].includes(getState().user.role)) return renderHome(); await renderDashboardView(false); } else if (route === 'admin') { if (getState().user.role !== 'admin') return renderHome(); await renderDashboardView(true); } else await renderHome(); } catch (error) { showToast(error.message); await renderHome(); } };
window.addEventListener('hashchange', renderRoute); window.addEventListener('auth:expired', () => { location.hash = '#/login'; showToast('Tu sesión expiró'); });
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('./sw.js').catch(() => {});
  });
}
await checkSession(); renderRoute();
