import { api } from './api.js';
import { API_ORIGIN } from './config.js';
import { getState } from './store.js';
import { escapeHtml, showToast } from './ui.js';

export const productState = { products: [], categories: [], filters: { search: '', category: '', listingType: '', minPrice: '', maxPrice: '', sort: 'recent', page: 1 }, pagination: {} };
export const loadCategories = async () => { const response = await api.get('/categories'); productState.categories = response.data; return productState.categories; };
export const loadProducts = async () => { const params = new URLSearchParams(Object.entries(productState.filters).filter(([, value]) => value !== '')); const response = await api.get(`/products?${params}`); productState.products = response.data.products || []; productState.pagination = response.data.pagination || {}; return productState.products; };
export const imageUrl = (image) => image ? (image.startsWith('http') ? image : `${API_ORIGIN}${image}`) : './assets/placeholder.svg';
export const imageFallback = (event) => { event.currentTarget.onerror = null; event.currentTarget.src = './assets/placeholder.svg'; };
export const rating = (average = 0) => `${'★'.repeat(Math.round(average))}${'☆'.repeat(5 - Math.round(average))}`;
export const productCard = (product) => { const favorites = getState().user?.favorites?.map(String) || []; const favorite = favorites.includes(String(product._id)); const typeLabel = product.listingType === 'service' ? 'Servicio' : 'Producto'; return `<article class="product-card"><div class="product-image-wrap"><img class="product-image" src="${imageUrl(product.images?.[0])}" onerror="this.onerror=null;this.src='./assets/placeholder.svg'" alt="${escapeHtml(product.name)}"><span class="product-category">${typeLabel} · ${escapeHtml(product.category)}</span><button class="icon-button favorite-button ${favorite ? 'is-favorite' : ''}" data-favorite="${product._id}" aria-label="${favorite ? 'Quitar de favoritos' : 'Agregar a favoritos'}">♡</button></div><div class="product-card-body"><h3>${escapeHtml(product.name)}</h3><p class="product-company">${escapeHtml(product.company)}</p><p class="product-description">${escapeHtml(product.desc)}</p><div class="product-meta"><strong>$${Number(product.price).toLocaleString('es-MX')}</strong><span class="rating">${rating(product.rating?.average)} <small>(${product.rating?.count || 0})</small></span></div><div class="product-actions"><a class="btn btn-secondary" href="#/product/${product._id}">Ver detalle</a><button class="btn btn-primary chat-product" data-chat-product="${product._id}">Chatear</button></div></div></article>`; };
export const renderProducts = (container) => { container.innerHTML = productState.products.length ? productState.products.map(productCard).join('') : `<div class="empty-state"><div class="empty-icon">⌕</div><h2>No hay productos</h2><p>Prueba con otra búsqueda o limpia los filtros.</p><button class="btn btn-secondary" data-clear-filters>Limpiar filtros</button></div>`; };
export const toggleFavorite = async (productId) => { const user = getState().user; if (!user) return showToast('Inicia sesión para guardar favoritos'); const response = await api.post(`/users/${user.id || user._id}/favorites/${productId}`, {}); user.favorites = response.data.favorites; localStorage.setItem('konekta_user', JSON.stringify(user)); showToast('Favoritos actualizados', 'success'); };
