import { api } from './api.js';
import { getState, setSession } from './store.js';
import { escapeHtml, showToast } from './ui.js';

const SETTINGS_KEY = 'konekta_settings';
const defaults = { theme: 'system', notifications: true, reducedMotion: false, compact: false };
const readSettings = () => ({ ...defaults, ...JSON.parse(localStorage.getItem(SETTINGS_KEY) || '{}') });
const applySettings = (settings = readSettings()) => { const root = document.documentElement; root.dataset.theme = settings.theme; root.classList.toggle('reduced-motion', settings.reducedMotion); root.classList.toggle('compact-ui', settings.compact); };
const saveSettings = (settings) => { localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings)); applySettings(settings); };
applySettings();
const settingsPanel = () => { const user = getState().user; const settings = readSettings(); return `<div class="settings-backdrop" id="settings-backdrop" hidden><section class="settings-panel" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div class="settings-heading"><div><p class="eyebrow">Cuenta</p><h2 id="settings-title">Perfil y ajustes</h2></div><button class="icon-button" id="settings-close" type="button" aria-label="Cerrar">×</button></div><form id="profile-form" class="settings-section"><h3>Tu perfil</h3><div class="settings-grid"><label class="form-field"><span>Nombre</span><input class="input" name="name" value="${escapeHtml(user?.name)}" minlength="2" maxlength="80" required></label><label class="form-field"><span>Correo electrónico</span><input class="input" name="email" type="email" value="${escapeHtml(user?.email)}" required></label><label class="form-field"><span>Foto de perfil</span><input class="input" name="avatar" type="file" accept="image/jpeg,image/png,image/webp,image/gif"><small class="field-hint">JPG, PNG o WebP.</small></label></div><p id="profile-form-error" class="field-error"></p><button class="btn btn-primary" type="submit">Guardar perfil</button></form><div class="settings-section"><h3>Experiencia</h3><label class="setting-row"><span><strong>Tema</strong><small>Adapta la apariencia de Konekta.</small></span><select class="input compact-select" id="setting-theme"><option value="system" ${settings.theme === 'system' ? 'selected' : ''}>Sistema</option><option value="light" ${settings.theme === 'light' ? 'selected' : ''}>Claro</option><option value="dark" ${settings.theme === 'dark' ? 'selected' : ''}>Oscuro</option></select></label><label class="setting-row"><span><strong>Notificaciones de mensajes</strong><small>Recibe avisos de nuevas conversaciones.</small></span><input type="checkbox" id="setting-notifications" ${settings.notifications ? 'checked' : ''}></label><label class="setting-row"><span><strong>Menos movimiento</strong><small>Reduce animaciones y transiciones.</small></span><input type="checkbox" id="setting-motion" ${settings.reducedMotion ? 'checked' : ''}></label><label class="setting-row"><span><strong>Vista compacta</strong><small>Reduce espacios para mostrar más contenido.</small></span><input type="checkbox" id="setting-compact" ${settings.compact ? 'checked' : ''}></label></div><div class="settings-section settings-footer"><span class="muted">Rol: ${escapeHtml(user?.role || 'usuario')}</span><button class="btn btn-secondary" id="settings-done" type="button">Listo</button></div></section></div>`; };
export const bindSettings = () => { const avatar = document.querySelector('#avatar-menu'); if (!avatar || avatar.dataset.settingsBound) return; avatar.dataset.settingsBound = 'true'; document.body.insertAdjacentHTML('beforeend', settingsPanel()); const backdrop = document.querySelector('#settings-backdrop'); const close = () => { backdrop.hidden = true; }; avatar.addEventListener('click', () => { backdrop.hidden = false; document.querySelector('#profile-form input')?.focus(); }); document.querySelector('#settings-close').addEventListener('click', close); document.querySelector('#settings-done').addEventListener('click', close); backdrop.addEventListener('click', (event) => { if (event.target === backdrop) close(); }); ['theme', 'notifications', 'motion', 'compact'].forEach((key) => { const input = document.querySelector(`#setting-${key}`); input?.addEventListener('change', (event) => { const settings = readSettings(); if (key === 'theme') settings.theme = event.target.value; if (key === 'notifications') settings.notifications = event.target.checked; if (key === 'motion') settings.reducedMotion = event.target.checked; if (key === 'compact') settings.compact = event.target.checked; saveSettings(settings); }); }); document.querySelector('#profile-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const button = form.querySelector('button[type="submit"]'); const errorBox = form.querySelector('#profile-form-error'); errorBox.textContent = ''; button.disabled = true; try { const response = await api.put(`/users/${getState().user.id || getState().user._id}`, new FormData(form)); setSession({ token: getState().token, user: response.data }); const name = document.querySelector('#avatar-menu'); if (name) name.textContent = response.data.name[0].toUpperCase(); showToast('Perfil actualizado', 'success'); } catch (error) { errorBox.textContent = error.message; } finally { button.disabled = false; } }); };
